apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment
  labels:
    app: capstone
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - image: katft/capstone
          imagePullPolicy: Always
          name: capstone
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-service
  labels:
    app: capstone
spec:
  type: LoadBalancer
  selector:
    app: capstone
  ports: 
    - port: 8000
      targetPort: 8080
      nodePort: 30000
      protocol: TCP